# Generated by Django 5.0.6 on 2026-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='artifact_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
